name = "waktu-solat-push"
main = "src/index.js"
compatibility_date = "2024-09-23"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "PUSH_SUBS"
id = "ebed209a44b149b2b9a0210ded557883"

[vars]
VAPID_SUBJECT = "mailto:zaimcherosli@gmail.com"
VAPID_PUBLIC_KEY = "BASJ8OMhJFQbaFMuH84DrMVTbRuJus2_I5HcuiHRtHSsVbjwLQ5uJqqtmoauWg4637-tPrtygyuSJ33FF5Fu5-Y"



